(load "cse.scm")






(display "\n- ---  Our cse: ----\n\n")
(cse-2 '((+ 1 (- 2 3) (- 2 3)) (+ 1 (- 2 3)  (- 2 3)) ))
(cse-2 '((b)))
(newline)
(cse-2 '((b) (a)))
(newline)
(cse-2 '((b) (b)))
(newline)
(cse-2 '(+ (* (- x y) (* x x))
(* x x)
(foo (- x y))
(goo (* (- x y) (* x x)))))
(newline)
(cse-2 '(f (g x)
(g (g x))
(h (g (g x)) (g x))
((g x) (g x))))
(newline)
(cse-2 '(list '(a b)
(list '(a b) '(c d))
(list '(a b) '(c d))))
(newline)
(cse-2 '(list (cons 'a 'b)
(cons 'a 'b)
(list (cons 'a 'b)
(cons 'a 'b))
(list (list (cons 'a 'b)
(cons 'a 'b)))))
(newline)
(cse-2 '(list '(a b) (a b) (a b)))
(newline)
(newline)


(display "\n- ---  Meirs cse: ----\n\n")

(load "cse.so")
(cse '((+ 1 (- 2 3) (- 2 3)) (+ 1 (- 2 3)  (- 2 3)) ))

(cse '((b)))
(newline)
(cse '((b) (a)))
(newline)
(cse '((b) (b)))
(newline)
(cse '(+ (* (- x y) (* x x))
(* x x)
(foo (- x y))
(goo (* (- x y) (* x x)))))
(newline)
(cse '(f (g x)
(g (g x))
(h (g (g x)) (g x))
((g x) (g x))))
(newline)
(cse '(list '(a b)
(list '(a b) '(c d))
(list '(a b) '(c d))))
(newline)
(cse '(list (cons 'a 'b)
(cons 'a 'b)
(list (cons 'a 'b)
(cons 'a 'b))
(list (list (cons 'a 'b)
(cons 'a 'b)))))
(newline)
(cse '(list '(a b) (a b) (a b)))
(newline)

