 
 WRITE_SOB_FRAC:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, FPARG(0));
  PUSH(INDD(R0, 2));
  PUSH(INDD(R0, 1));
  CALL(WRITE_INTEGER);
  DROP(1);
  PUSH('/');
  CALL(PUTCHAR);
  DROP(1);
  CALL(WRITE_INTEGER);
  DROP(1);
  POP(FP);
  RETURN;